export const WZ_CODES: Record<string, { code: string; label: string }[]> = {
  "maschinenbau": [{ code: "28", label: "Maschinenbau" }],
  "metall": [{ code: "24", label: "Metallerzeugung" }, { code: "25", label: "Metallerzeugnisse" }],
  "metallverarbeitung": [{ code: "25", label: "Metallerzeugnisse" }],
  "elektro": [{ code: "26", label: "Elektronik" }, { code: "27", label: "Elektrische Ausrüstungen" }],
  "elektrotechnik": [{ code: "27", label: "Elektrische Ausrüstungen" }],
  "elektronik": [{ code: "26", label: "Elektronik" }],
  "it": [{ code: "62", label: "IT-Dienstleistungen" }, { code: "63", label: "Informationsdienstleistungen" }],
  "software": [{ code: "62", label: "IT-Dienstleistungen" }],
  "informatik": [{ code: "62", label: "IT-Dienstleistungen" }],
  "bau": [{ code: "41", label: "Hochbau" }, { code: "42", label: "Tiefbau" }, { code: "43", label: "Spezialisierter Bau" }],
  "hochbau": [{ code: "41", label: "Hochbau" }],
  "tiefbau": [{ code: "42", label: "Tiefbau" }],
  "handwerk": [{ code: "41", label: "Hochbau" }, { code: "43", label: "Spezialisierter Bau" }],
  "handel": [{ code: "45", label: "KFZ-Handel" }, { code: "46", label: "Grosshandel" }, { code: "47", label: "Einzelhandel" }],
  "grosshandel": [{ code: "46", label: "Grosshandel" }],
  "einzelhandel": [{ code: "47", label: "Einzelhandel" }],
  "kfz": [{ code: "45", label: "KFZ-Handel und -Reparatur" }],
  "auto": [{ code: "45", label: "KFZ-Handel und -Reparatur" }],
  "logistik": [{ code: "49", label: "Landverkehr" }, { code: "52", label: "Lagerei" }],
  "transport": [{ code: "49", label: "Landverkehr" }, { code: "50", label: "Schifffahrt" }],
  "spedition": [{ code: "49", label: "Landverkehr" }, { code: "52", label: "Lagerei" }],
  "lager": [{ code: "52", label: "Lagerei" }],
  "gesundheit": [{ code: "86", label: "Gesundheitswesen" }],
  "medizin": [{ code: "86", label: "Gesundheitswesen" }],
  "pflege": [{ code: "87", label: "Heime" }, { code: "88", label: "Sozialwesen" }],
  "soziales": [{ code: "88", label: "Sozialwesen" }],
  "healthcare": [{ code: "86", label: "Gesundheitswesen" }, { code: "87", label: "Heime" }],
  "gastronomie": [{ code: "56", label: "Gastronomie" }],
  "restaurant": [{ code: "56", label: "Restaurants" }],
  "gastgewerbe": [{ code: "55", label: "Beherbergung" }, { code: "56", label: "Gastronomie" }],
  "hotel": [{ code: "55", label: "Beherbergung" }],
  "immobilien": [{ code: "68", label: "Grundstücks-/Wohnungswesen" }],
  "chemie": [{ code: "20", label: "Chemische Erzeugnisse" }],
  "pharma": [{ code: "21", label: "Pharmazeutische Erzeugnisse" }],
  "pharmazeutisch": [{ code: "21", label: "Pharmazeutische Erzeugnisse" }],
  "kunststoff": [{ code: "22", label: "Gummi-/Kunststoffwaren" }],
  "gummi": [{ code: "22", label: "Gummi-/Kunststoffwaren" }],
  "glas": [{ code: "23", label: "Glas/Keramik/Verarbeitung v. Steinen" }],
  "keramik": [{ code: "23", label: "Glas/Keramik" }],
  "automotive": [{ code: "29", label: "Kraftwagen und -teile" }],
  "fahrzeugbau": [{ code: "29", label: "Kraftwagen und -teile" }],
  "fahrzeug": [{ code: "29", label: "Kraftwagen und -teile" }],
  "schiffbau": [{ code: "30", label: "Sonstiger Fahrzeugbau" }],
  "luft": [{ code: "30", label: "Sonstiger Fahrzeugbau" }],
  "nahrungsmittel": [{ code: "10", label: "Nahrungsmittelherstellung" }],
  "lebensmittel": [{ code: "10", label: "Nahrungsmittelherstellung" }],
  "ernaehrung": [{ code: "10", label: "Nahrungsmittelherstellung" }],
  "baeckerei": [{ code: "10", label: "Nahrungsmittelherstellung" }],
  "getraenke": [{ code: "11", label: "Getränkeherstellung" }],
  "tabak": [{ code: "12", label: "Tabakverarbeitung" }],
  "textil": [{ code: "13", label: "Textilien" }, { code: "14", label: "Bekleidung" }],
  "bekleidung": [{ code: "14", label: "Bekleidung" }],
  "leder": [{ code: "15", label: "Leder/Lederwaren/Schuhe" }],
  "holz": [{ code: "16", label: "Holz/Kork/Flecht" }],
  "papier": [{ code: "17", label: "Papier/Pappe" }],
  "druck": [{ code: "18", label: "Druckerzeugnisse" }],
  "druckerei": [{ code: "18", label: "Druckerzeugnisse" }],
  "verpackung": [{ code: "22", label: "Gummi-/Kunststoffwaren" }],
  "moebel": [{ code: "31", label: "Möbelherstellung" }],
  "schmuck": [{ code: "32", label: "Sonstige Waren" }],
  "spielzeug": [{ code: "32", label: "Sonstige Waren" }],
  "reparatur": [{ code: "33", label: "Reparatur v. Maschinen" }],
  "energie": [{ code: "35", label: "Energieversorgung" }],
  "strom": [{ code: "35", label: "Energieversorgung" }],
  "wasser": [{ code: "36", label: "Wasserversorgung" }],
  "abfall": [{ code: "38", label: "Abfallentsorgung" }],
  "entsorgung": [{ code: "38", label: "Abfallentsorgung" }],
  "beratung": [{ code: "70", label: "Unternehmensberatung" }],
  "consulting": [{ code: "70", label: "Unternehmensberatung" }],
  "unternehmensberatung": [{ code: "70", label: "Unternehmensberatung" }],
  "steuerberater": [{ code: "69", label: "Rechts-/Steuerberatung" }],
  "steuerberatung": [{ code: "69", label: "Rechts-/Steuerberatung" }],
  "rechtsanwalt": [{ code: "69", label: "Rechts-/Steuerberatung" }],
  "anwalt": [{ code: "69", label: "Rechts-/Steuerberatung" }],
  "architektur": [{ code: "71", label: "Architektur-/Ingenieurbüros" }],
  "architekt": [{ code: "71", label: "Architektur-/Ingenieurbüros" }],
  "ingenieur": [{ code: "71", label: "Architektur-/Ingenieurbüros" }],
  "planungsbuero": [{ code: "71", label: "Architektur-/Ingenieurbüros" }],
  "forschung": [{ code: "72", label: "Forschung und Entwicklung" }],
  "werbung": [{ code: "73", label: "Werbung und Marktforschung" }],
  "marketing": [{ code: "73", label: "Werbung und Marktforschung" }],
  "design": [{ code: "74", label: "Sonstige freiberufliche Tätigkeiten" }],
  "reinigung": [{ code: "81", label: "Gebäudebetreuung/Reinigung" }],
  "hausmeister": [{ code: "81", label: "Gebäudebetreuung/Reinigung" }],
  "gebaeudereinigung": [{ code: "81", label: "Gebäudebetreuung/Reinigung" }],
  "sicherheit": [{ code: "80", label: "Wach-/Sicherheitsdienste" }],
  "wachdienst": [{ code: "80", label: "Wach-/Sicherheitsdienste" }],
  "zeitarbeit": [{ code: "78", label: "Arbeitsvermittlung/-überlassung" }],
  "personal": [{ code: "78", label: "Arbeitsvermittlung/-überlassung" }],
  "personaldienstleistung": [{ code: "78", label: "Arbeitsvermittlung/-überlassung" }],
  "reisebüro": [{ code: "79", label: "Reisebüros/-veranstalter" }],
  "reise": [{ code: "79", label: "Reisebüros/-veranstalter" }],
  "finanz": [{ code: "64", label: "Finanzdienstleistungen" }],
  "bank": [{ code: "64", label: "Finanzdienstleistungen" }],
  "versicherung": [{ code: "65", label: "Versicherungen" }],
  "buchhaltung": [{ code: "69", label: "Rechts-/Steuerberatung" }],
  "telekommunikation": [{ code: "61", label: "Telekommunikation" }],
  "telekom": [{ code: "61", label: "Telekommunikation" }],
  "medien": [{ code: "59", label: "Film/TV/Kino" }, { code: "60", label: "Rundfunk" }],
  "verlag": [{ code: "58", label: "Verlage" }],
  "bildung": [{ code: "85", label: "Erziehung und Unterricht" }],
  "schule": [{ code: "85", label: "Erziehung und Unterricht" }],
  "training": [{ code: "85", label: "Erziehung und Unterricht" }],
  "sport": [{ code: "93", label: "Sport/Unterhaltung/Erholung" }],
  "freizeit": [{ code: "93", label: "Sport/Unterhaltung/Erholung" }],
  "dienstleistung": [{ code: "82", label: "Wirtschaftliche DL" }],
};

export function lookupWzCode(term: string): { code: string; label: string }[] {
  const lower = term.toLowerCase().trim();
  return WZ_CODES[lower] || [];
}

export function getWzLabel(code: string): string {
  for (const entries of Object.values(WZ_CODES)) {
    for (const entry of entries) {
      if (entry.code === code) return entry.label;
    }
  }
  return `WZ ${code}`;
}
